config/routes.rb
DatabaseApp::Application.routes.draw do
  devise_for :members

root :to => 'home#index'

devise_for :members,:controllers => { :registrations =>'registration'}
match 'dashboard' => 'home#dashboard'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :member
end

app/models/member.rb
class Member < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username has_one :contact
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController
def new

@member= Member.new
@contact= Contact.new
end

def create
  @member = Member.new
  @member.username = params[:member][:username]
  @member.email = params[:member][:email]
  @member.password = params[:member][:password]
  @member.password_confirmation = params[:member][:password_confirmation]

  @contact = Contact.new
  @contact.mobile = params[:contact][:mobile]
  @contact.address = params[:contact][:address]
  @member.valid?

  if @member.errors.blank?
  @member.save
  @contact.member = @member
  @contact.save
  redirect_to dashboard_path
  else
  render :action => "new"
  end
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/views/home/dashboard.html.erb
<p>hi welcome to Ruby world. you have successfully registered to your rails club account</p>
<%= link_to "Sign out", destroy_member_session_path, :method => :delete %>

app/views/home/index.html.erb
<% if member_signed_in? %>

<h3>you have sucessfully signed in</h3>
<%= link_to "Sign Out", destroy_mumber_session_path, :method => :delete %>

<% else %>
<h1> welcome to rails world! </h1>
<%= link_to "Sign In", new_member_session_path, :mehtod => :get %>
<%= link_to "Sign up", new_member_registration_path, :method => :get %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DatabaseApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>